// Generated by LiveScript 1.6.0
(function(){
  var mainnet, testnet, color, type, enabled, token, image, usdInfo, out$ = typeof exports != 'undefined' && exports || this;
  out$.mainnet = mainnet = {
    decimals: 18,
    txFee: '0.0014',
    txFeeOptions: {
      auto: '0.0014',
      cheap: '0.00014'
    },
    messagePrefix: 'Ethereum',
    mask: '0x0000000000000000000000000000000000000000',
    api: {
      provider: 'eth',
      web3Provider: 'https://ethereumclassic.network',
      url: 'http://gastracker.io',
      addressSubUrl: 'addr',
      apiUrl: 'https://api.etherscan.io/api'
    }
  };
  out$.testnet = testnet = {
    decimals: 18,
    disabled: true,
    txFee: '0.0014',
    txFeeOptions: {
      auto: '0.0014',
      cheap: '0.00014'
    },
    messagePrefix: 'Ethereum',
    mask: '0x0000000000000000000000000000000000000000',
    api: {
      provider: 'eth',
      web3Provider: 'https://ropsten.infura.io/UoCkF4efTrbEGU8Qpcs0',
      url: 'https://ropsten.etherscan.io',
      apiUrl: 'https://api-ropsten.etherscan.io/api'
    }
  };
  out$.color = color = '#71DF8F';
  out$.type = type = 'coin';
  out$.enabled = enabled = true;
  out$.token = token = 'etc';
  out$.image = image = 'https://bitsettle.com/images/sp/1321-dbbd894924b65cc449f43c7bc7e9325e0478bbd4e9723249ac029fc6279cb55e.png';
  out$.usdInfo = usdInfo = "url(https://min-api.cryptocompare.com/data/pricemulti?fsyms=BTC,ETH,LTC,DASH,XEM,USDT,ETC&tsyms=USD).ETC.USD";
}).call(this);
